import { useEffect } from "react";
import Head from "next/head";
import Filter from "../components/search_page/filter";
import Cover from "../components/search_page/cover";
import Item from "../components/search_page/item";
import Layout from "../layout/pageLayout";
import image from "../assets/Audi-A4.jpg";
import { Grid } from "@mui/material";
import axios from "axios";

import { api_url, config } from "../store/config";

import { getCars } from "../store/reducer/cars";
import { getImage } from "../store/reducer/profile";
import { storeWrapper } from "../store/index";

function Cars(props) {

  return (
    <div>
      <Head>
        <title>Cars</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Layout>
        <Cover />
        <Filter />
        <Grid container>
          <Grid item sm={9}>
            {/* <GetCars /> */}
            {props.cars?.data?.map((ele, i) => (
              <Item key={i} image={image.src} car={ele} />
            ))}
          </Grid>
          <Grid item sm={3}>
          </Grid>
        </Grid>
      </Layout>
    </div>
  );
}

export const getServerSideProps = storeWrapper.getServerSideProps(
  (store) => async ({req, res}) => {
    const result = await axios.get(`${api_url}/vehicle?total=true`, {
      params: null,
      headers: {
        "Authorization": `Bearer ${JSON.parse(req.cookies.user)?.data?.accessToken}`,
        "Content-Type": "application/json",
      },
    });
    var newArr =[]
     result.data.data?.map(ele => {
      axios.get(`${api_url}/static/${ele.image}`, {
        params: null,
        headers: {
          "Authorization": `Bearer ${JSON.parse(req.cookies.user)?.data?.accessToken}`,
          "Content-Type": "application/json",
        },
      }).then(response => {
        newArr.push({
          id: ele.image,
          image: response.data
        })
      })
      console.log("newArr: ", newArr)
      return newArr
    })
    console.log("Images: ", newArr)
    return { props: { cars: result.data} };
  }
);

export default Cars;
