import Head from "next/head";

import Cover from "../components/home/cover";
import Layout from "../layout/pageLayout";
import SectionContainer from "../components/home/second_section";
import ThirdSection from '../components/home/third_section';
import ForthSection from '../components/home/fourth_section';
import FifthSection from '../components/home/fifthSection';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Layout>
        <Cover />
        <SectionContainer />
        <ThirdSection />
        <ForthSection />
        <FifthSection />
      </Layout>
    </div>
  );
}
