import Head from "next/head";

import Filter from "../components/search_page/filter";
import Cover from "../components/search_page/cover";
import Item from "../components/search_page/item";
import Layout from "../layout/pageLayout";
import image from "../assets/Audi-A4.jpg";
import { Grid } from "@mui/material";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Layout>
        <Cover />
        <Filter />
        <Grid container>
          <Grid sm={9}>
            {[...Array(5)].map((ele, i) => (
              <Item key={i} image={image.src} name="Audi A4" />
            ))}
          </Grid>
          <Grid sm={3}>

          </Grid>
        </Grid>
      </Layout>
    </div>
  );
}
