import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Form from "../container/register/signup";
import {Background} from '../components/register/form-bkg'
import {Wrapper, Container} from '../components/register/style'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Signup</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
        <Wrapper>
            <Container>
                <Form />
                <Background />
            </Container>
        </Wrapper>
    </div>
  )
}